[package]
name = "sendgrid-futures3"
version = "0.0.1"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
description = "An unofficial client library for the SendGrid API (futures3 version)"
repository = "https://github.com/jbg/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"
keywords = ["email"]
readme = "README.md"

[dependencies]
data-encoding = "2.1"
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
reqwest = { version = "0.9", default-features = false, features = ["rustls-tls", "trust-dns"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
failure = "0.1.2"
failure_derive = "0.1.2"
