[package]
name = "sendgrid-futures3"
version = "0.0.1"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
description = "An unofficial client library for the SendGrid API (futures3 version)"
repository = "https://github.com/jbg/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"
keywords = ["email"]
readme = "README.md"
edition = "2018"

[dependencies]
data-encoding = "2.1"
failure = { version = "0.1.5", default-features = false, features = ["derive"] }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
http = "0.1.18"
hyper = "0.12.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "1.7"
