[package]
name = "sendgrid-futures3"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
description = "An unofficial client library for the SendGrid API (futures3 version)"
repository = "https://github.com/jbg/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"
keywords = ["email"]
readme = "README.md"
edition = "2018"

[dependencies]
data-encoding = "2.1"
failure = { version = "0.1.5", default-features = false, features = ["derive"] }
futures-preview = "0.3.0-alpha.19"
http = "0.1.18"
hyper = { version = "0.13.0-alpha.4", features = ["nightly", "unstable-stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.1.0"
